# SegForestNet Configuration for Windows
device: 'cpu'  # Will be automatically set to cuda if available

# Training parameters
batch_size: 8
num_epochs: 100
learning_rate: 0.001
weight_decay: 0.0001

# Model parameters
SegForestNet_params:
  input_shape: [3, 256, 256]  # [channels, height, width]
  num_classes: 6  # Adjust based on your dataset
  trees:
    - graph: "BSPTree(2, Line)"  # Basic tree structure
      outputs: [0, 1, 2, 3, 4, 5]  # All classes

# Dataset parameters
dataset:
  root_dir: "datasets/iris"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  augmentation:
    enable: true
    rotation_range: 15
    width_shift_range: 0.1
    height_shift_range: 0.1
    zoom_range: 0.1

# Logging and checkpoints
output_dir: "outputs"
save_frequency: 10
log_frequency: 100 